# Generated by Django 3.1 on 2020-08-29 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('king', models.CharField(choices=[('Кошка', 'Cat'), ('Собака', 'Dog'), ('Попугай', 'parrot')], default='', max_length=7)),
                ('photo', models.ImageField(blank=True, upload_to='img/%Y/%m/%d')),
            ],
        ),
    ]
