# Generated by Django 3.1 on 2020-08-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='king',
            field=models.CharField(choices=[('Кошка', 'Cat'), ('Собака', 'Dog'), ('Попугай', 'Parrot')], default='', max_length=7),
        ),
    ]
