# Generated by Django 3.1 on 2020-08-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_animal_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен'), ('Не определен', 'Не определен')], default='Не определен', max_length=12),
        ),
    ]
